<a href="https://colab.research.google.com/github/bahadirbolatt/Veri-Bilimi-in-Python-ve-Tensorflow/blob/main/NumpyGiris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

## **numpy array**

In [ ]:
benimListem = [20, 30 ,40]

In [ ]:
type(benimListem)

list

In [ ]:
np.array(benimListem)

array([20, 30, 40])

In [ ]:
matrixListesi = [[10, 20 ,30],[20, 30, 40],[30, 40, 50]]

In [ ]:
type(matrixListesi)

list

In [ ]:
matrixListesi[1][0]

20

In [ ]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## **arange**

In [ ]:
list(range(0,10)) #range ile 0-10 arası dizi oluşturma

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(0,10) #numpy ile 0-10 arası dizi oluşturma

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,2) #ikişerli dizi oluşturma

array([0, 2, 4, 6, 8])

## **zeros**

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((10,3)) #10 satırlı 3 sütunlu matrix dizi

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## **linspace**

In [ ]:
np.linspace(0, 20, 5) #eşit olarak aralık bırakılmış eşit dizi demektir. 0 ila 20 arasında 5 boşluk bırakarak bir dizi oluşturur.

array([ 0.,  5., 10., 15., 20.])

In [ ]:
np.linspace(0,10,20) #bu sefer floatlara girecek.

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [ ]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

## **eye**

In [ ]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## **random**

In [ ]:
np.random.randn(5)

array([ 0.49094671, -1.90649615,  1.0360874 ,  0.52602505,  1.47424874])

In [ ]:
np.random.randn(3,5)

array([[ 0.57731001, -0.62866918,  0.67979168, -0.9187684 , -0.43752134],
       [-0.61944274,  1.20432635,  0.17485842,  0.41481244,  0.07078795],
       [-2.4616275 ,  0.92525296, -0.36341377,  1.52180684, -1.8919583 ]])

In [ ]:
np.random.randint(1,10)  #1 döner 10 dönmez

7

In [ ]:
np.random.randint(1, 500, 5)

array([215, 378,  64,  19, 281])

In [ ]:
np.random.randint(1, 10, 20)

array([9, 8, 9, 9, 3, 5, 7, 2, 6, 9, 5, 6, 3, 6, 8, 6, 5, 2, 5, 5])

In [ ]:
benimNumpyDizim = np.arange(30)

In [ ]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
benimRandomDizim = np.random.randint(0, 100, 30)

In [ ]:
benimRandomDizim

array([20, 14, 93, 81, 31, 50, 93, 81, 41, 93, 64, 82,  3, 88, 23, 14, 17,
       46, 44, 49, 75, 14, 55, 86, 46, 70, 55, 41, 79, 74])

## **numpy dizi methodları**